require "bigdecimal"
require "bigdecimal/util"

module ContractsHelper
  # Dispatches by ABI output shape: tuples → (name: val, ...), arrays → [...],
  # scalars → format_abi_value. Prefer this over format_abi_value when you have
  # the full output hash (with components for tuples).
  def format_abi_output(value, output)
    type = output["type"].to_s
    if type == "tuple"
      format_tuple(value, Array(output["components"]))
    elsif type.start_with?("tuple[")
      suffix = type.sub(/\Atuple/, "")
      if suffix == "[]"
        "[" + Array(value).map { |v| format_tuple(v, Array(output["components"])) }.join(", ") + "]"
      else
        # Fixed-size tuple array like tuple[2]: treat as array of tuples
        "[" + Array(value).map { |v| format_tuple(v, Array(output["components"])) }.join(", ") + "]"
      end
    else
      format_abi_value(value, type)
    end
  end

  # Format a single decoded ABI value for inline display.
  # Types handled: uint/int*, bool, address, string, bytes*, arrays (shallow).
  def format_abi_value(value, type)
    case type
    when /\A(u?int)(\d*)\z/
      format_integer(value)
    when "bool"
      value ? "true" : "false"
    when "address"
      value.to_s.downcase
    when "string"
      value.to_s.length > 80 ? "#{value.to_s[0, 77]}..." : value.to_s
    when /\Abytes\d+\z/, "bytes"
      "0x" + value.to_s.unpack1("H*")
    when /\A(.+)\[\]\z/
      inner = $1
      "[" + Array(value).map { |v| format_abi_value(v, inner) }.join(", ") + "]"
    else
      value.inspect
    end
  end

  # Given a Multicall3Client::Result + ABI function hash, return an inline HTML-safe
  # string ready to drop next to the function name. Returns nil if there's nothing useful.
  def render_live_result(result, fn)
    return nil unless result

    if !result.success
      return content_tag(:span, "reverted", class: "text-error text-xs font-mono")
    end

    outputs = Array(fn["outputs"])
    return nil if outputs.empty? || result.values.empty?

    parts = result.values.each_with_index.map do |v, i|
      smart_format_output(v, outputs[i], fn)
    end

    content_tag(:span, "→ #{parts.join(', ')}", class: "text-success text-xs font-mono break-all")
  end

  # User-facing block explorer base URL per supported chain. Used by
  # dual-link renderers that want the "↗ Etherscan" counterpart to an
  # on-smarts-md link. Returns nil for unknown chains.
  EXPLORER_BASE_URLS = {
    "eth"      => "https://etherscan.io",
    "base"     => "https://basescan.org",
    "arbitrum" => "https://arbiscan.io",
    "optimism" => "https://optimistic.etherscan.io",
    "polygon"  => "https://polygonscan.com"
  }.freeze

  def explorer_address_url(chain, address)
    base = EXPLORER_BASE_URLS[chain.slug]
    return nil unless base

    "#{base}/address/#{address}"
  end

  def explorer_name(chain)
    case chain.slug
    when "eth"      then "Etherscan"
    when "base"     then "Basescan"
    when "arbitrum" then "Arbiscan"
    when "optimism" then "Etherscan"
    when "polygon"  then "Polygonscan"
    else "explorer"
    end
  end

  # Truncated "0xa0b8…eb48" for inline display. First 6 + last 4.
  def truncate_address(addr)
    return nil unless addr.is_a?(String) && addr.start_with?("0x") && addr.length >= 12

    "#{addr[0, 6]}…#{addr[-4..]}"
  end

  # Formats a wei amount to a human-friendly eth-units string rounded to 2dp.
  # Returns nil for nil input.
  def format_native_balance(wei, symbol)
    return nil if wei.nil?

    eth = wei.to_d / BigDecimal("1e18")
    rounded = eth.round(2, BigDecimal::ROUND_DOWN)
    whole, frac = rounded.to_s("F").split(".")
    whole_fmt = whole.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\1,').reverse
    frac_padded = (frac.to_s + "00")[0, 2]
    body = frac_padded == "00" ? whole_fmt : "#{whole_fmt}.#{frac_padded}"
    "#{body} #{symbol}"
  end

  # Higher-precision version for developers. Six decimals, no rounding-down.
  def format_native_balance_precise(wei, symbol)
    return nil if wei.nil?

    eth = wei.to_d / BigDecimal("1e18")
    rounded = eth.round(6, BigDecimal::ROUND_DOWN)
    whole, frac = rounded.to_s("F").split(".")
    whole_fmt = whole.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\1,').reverse
    frac_padded = (frac.to_s + "000000")[0, 6]
    "#{whole_fmt}.#{frac_padded} #{symbol}"
  end

  # Small inline marker shown next to AI-generated doc text. Returns nil if
  # the source is "real" or missing so callers can safely `<%= %>` it.
  def ai_badge(source_value)
    return nil unless source_value == "ai"

    content_tag(:span, "✨ AI", class: "badge badge-xs badge-ghost opacity-70 ml-1",
                title: "Generated by Claude from the ABI, not the original source.")
  end

  # Builds a human-readable signature with named parameters:
  # balanceOf(account: address)  —  omits names when unnamed.
  def function_signature_with_params(fn)
    inputs = Array(fn["inputs"])
    return "#{fn['name']}()" if inputs.empty?

    parts = inputs.map do |i|
      name = i["name"].to_s
      name.empty? ? i["type"] : "#{name}: #{i['type']}"
    end

    "#{fn['name']}(#{parts.join(', ')})"
  end

  # Same as format_abi_output but with protocol awareness: ERC-20 totalSupply()
  # returns raw uint256 wei, which is unreadable. If @classification marks this
  # contract as ERC-20 and decimals()/symbol() live values are available, render
  # "55,046,395,721.81 USDC" instead of "55,046,395,721,805,492".
  def smart_format_output(value, output, fn)
    if erc20_amount_function?(fn, output)
      scaled = scale_erc20_amount(value)
      return scaled if scaled
    end
    format_abi_output(value, output)
  end

  private

  def erc20_amount_function?(fn, output)
    return false unless @classification&.protocol_key == "erc20"
    return false unless fn["name"] == "totalSupply"

    output["type"].to_s.match?(/\Auint\d*\z/)
  end

  def scale_erc20_amount(raw)
    return nil unless raw.is_a?(Integer)
    decimals = erc20_decimals
    return nil unless decimals

    scaled = (raw.to_d / (BigDecimal(10) ** decimals)).round(2, BigDecimal::ROUND_DOWN)
    whole, frac = scaled.to_s("F").split(".")
    whole_formatted = whole.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\1,').reverse
    frac_padded = (frac.to_s + "00")[0, 2]
    body = frac_padded == "00" ? whole_formatted : "#{whole_formatted}.#{frac_padded}"
    symbol = erc20_symbol
    symbol ? "#{body} #{symbol}" : body
  end

  def erc20_decimals
    live_value("decimals()").then { |v| v.is_a?(Integer) ? v : nil }
  end

  def erc20_symbol
    live_value("symbol()").then { |v| v.is_a?(String) ? v : nil }
  end

  def live_value(signature)
    result = @live_values&.dig(signature)
    return nil unless result&.success && result.values.any?
    result.values.first
  end

  def format_integer(n)
    return n.to_s unless n.is_a?(Integer)
    n.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\1,').reverse
  end

  def format_tuple(value, components)
    parts = components.each_with_index.map do |comp, i|
      v = Array(value)[i]
      rendered = format_abi_output(v, comp)
      name = comp["name"].to_s
      name.empty? ? rendered : "#{name}: #{rendered}"
    end
    "(#{parts.join(', ')})"
  end
end
